### ISSUE TITLE
No version set for erlang

### ISSUE THREAD

**Issue by vassilevsky** [Stratus3D/asdf-rebar#6]
Hi :)

I tried the following:

```
$ asdf install rebar 3.5.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   120    0   120    0     0    173      0 --:--:-- --:--:-- --:--:--   173
100  280k    0  280k    0     0   123k      0 --:--:--  0:00:02 --:--:--  218k
No version set for erlang; please run `asdf <global | local> erlang <version>`
```

But:

```
$ cat .tool-versions
erlang 18.3
```

What did I do wrong? :)

**Comment by vassilevsky** [comment]
When I ran `asdf global erlang 18.3`, it worked.

**Comment by Stratus3D** [comment]
Sorry for the late response. I would first verify that Erlang 18.3 was actually installed on your system and available in the directory that you ran `asdf install rebar 3.5.2` in. Just running `erl` in that same directory should give you the version info you need.

**Comment by Stratus3D** [comment]
I'm going to close this issue now. If you have any other questions feel free to reply.

**Comment by aikomastboom** [comment]
I have this same issue.

this is my `.tool-versions` 
```
elixir 1.15.2-otp-26
erlang 26.0.2
gleam 0.30.0
rebar 3.22.0
```

running `erl` in this folder works just fine:
```
$ erl
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Eshell V14.0.2 (press Ctrl+G to abort, type help(). for help)
1> 
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
a
```

I have no `global` asdf applications installed as I like to keep my dependencies localized to folder I am development in/on.
