### ISSUE TITLE
3.7.4 won't install without curl error

### ISSUE THREAD

**Issue by alanvoss** [Stratus3D/asdf-rebar#9]
```
> asdf install rebar 3.7.4
** Resuming transfer from byte position 317253
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   120    0   120    0     0    297      0 --:--:-- --:--:-- --:--:--   297
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
```

**Comment by alanvoss** [comment]
`3.7.3` worked fine.

`.tool-versions`, fwiw:

```erlang 21.1.4
elixir 1.7.4```

**Comment by alanvoss** [comment]
Hope you are good, @Stratus3D !

**Comment by Stratus3D** [comment]
Interesting, appears curl is trying to re-download the archive, and it looks like Github doesn't support specifying bytes ranges for downloads so it fails to resume the download. I've removed the `-C` flag for curl so it will download the full archive each time, even if the previous download failed. The rebar archive is pretty small so I don't think this will be a problem.

**Comment by alanvoss** [comment]
👍

**Comment by Stratus3D** [comment]
I'm doing well @alanvoss. Hope you are enjoying the new work!
